# Generated by Django 6.1 on 2026-08-15 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diseases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Reference title or article heading', max_length=200)),
                ('symptoms_summary', models.TextField(help_text='Detailed description of visible field symptoms')),
                ('causes', models.TextField(help_text='Pathogen, fungal, bacterial or environmental cause')),
                ('favorable_conditions', models.TextField(help_text='Temperature, humidity or moisture conditions encouraging spread')),
                ('treatment_immediate', models.TextField(help_text='Immediate non-chemical or field care steps')),
                ('treatment_management', models.TextField(help_text='Longer term cultural or approved management practices')),
                ('prevention_methods', models.TextField(help_text='Crop spacing, sanitation, resistant varieties, crop rotation')),
                ('monitoring_guidance', models.TextField(help_text='When and how often to inspect crops, when to seek expert help')),
                ('source_reference', models.CharField(default='Verified ICAR / Agricultural University Guidelines', max_length=255)),
                ('last_reviewed', models.DateField(auto_now=True)),
                ('disease', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_source', to='diseases.disease')),
            ],
            options={
                'verbose_name': 'Knowledge Base Entry',
                'verbose_name_plural': 'Knowledge Base Entries',
            },
        ),
    ]
