# Generated by Django 6.1 on 2026-08-15 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='English crop name e.g. Tomato', max_length=100, unique=True)),
                ('name_hi', models.CharField(blank=True, help_text='Hindi crop name e.g. टमाटर', max_length=100, null=True)),
                ('scientific_name', models.CharField(blank=True, max_length=150, null=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('icon_class', models.CharField(default='fa-seedling', help_text='FontAwesome icon class e.g. fa-pepper-hot', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='crops/')),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Crop',
                'verbose_name_plural': 'Crops',
                'ordering': ['name'],
            },
        ),
    ]
