# Generated by Django 6.1 on 2026-08-15 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_hi', models.CharField(blank=True, max_length=100, null=True)),
                ('code', models.CharField(help_text='Unique key identifier e.g. brown_spots', max_length=50, unique=True)),
                ('icon', models.CharField(default='fa-leaf', max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('name_hi', models.CharField(blank=True, max_length=150, null=True)),
                ('scientific_name', models.CharField(blank=True, max_length=150, null=True)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('LOW', 'Low Risk / Mild'), ('MEDIUM', 'Moderate Risk'), ('HIGH', 'High Severity / Critical')], default='MEDIUM', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='diseases/')),
                ('source_reference', models.CharField(default='Verified Agricultural Knowledge Base', max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diseases', to='crops.crop')),
            ],
            options={
                'ordering': ['crop', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DiseaseSymptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=True, help_text='True if this is a primary diagnostic symptom')),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diseases.disease')),
                ('symptom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diseases.symptom')),
            ],
            options={
                'unique_together': {('disease', 'symptom')},
            },
        ),
        migrations.AddField(
            model_name='disease',
            name='symptoms',
            field=models.ManyToManyField(related_name='diseases', through='diseases.DiseaseSymptom', to='diseases.symptom'),
        ),
        migrations.AlterUniqueTogether(
            name='disease',
            unique_together={('name', 'crop')},
        ),
    ]
