# Generated by Django 6.1 on 2026-08-15 19:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crops', '0001_initial'),
        ('diseases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PROCESSING', max_length=20)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('is_low_confidence', models.BooleanField(default=False)),
                ('is_inconsistent', models.BooleanField(default=False)),
                ('explanation', models.TextField(blank=True)),
                ('image_retention_status', models.CharField(choices=[('TEMPORARY', 'Temporary Storage'), ('PROCESSED', 'Processed & Retained for Model Training'), ('STORED_WITH_USER_PERMISSION', 'Stored with User Permission'), ('DELETED', 'Deleted per Privacy Policy')], default='PROCESSED', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='crops.crop')),
                ('predicted_disease', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnoses', to='diseases.disease')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnoses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Diagnoses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DiagnosisAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_noticed', models.CharField(default='Today', help_text='e.g. Today, 2-3 days ago, About a week ago, >1 week ago', max_length=50)),
                ('affected_parts', models.JSONField(default=list, help_text="e.g. ['Leaves', 'Stem']")),
                ('visible_symptoms', models.JSONField(default=list, help_text="e.g. ['Yellowing', 'Brown spots']")),
                ('is_spreading', models.CharField(default='Not sure', max_length=20)),
                ('weather_condition', models.CharField(default='Humid', max_length=50)),
                ('treatment_applied', models.CharField(default='No', max_length=20)),
                ('treatment_details', models.TextField(blank=True)),
                ('diagnosis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='diagnosis.diagnosis')),
            ],
        ),
        migrations.CreateModel(
            name='DiagnosisImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_number', models.PositiveSmallIntegerField(default=1, help_text='Slot index 1 to 5')),
                ('image', models.ImageField(upload_to='diagnosis_uploads/%Y/%m/%d/')),
                ('is_valid', models.BooleanField(default=True)),
                ('quality_warning', models.CharField(blank=True, max_length=255, null=True)),
                ('prediction_prob', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='diagnosis.diagnosis')),
            ],
            options={
                'ordering': ['slot_number'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_helpful', models.BooleanField(default=True)),
                ('reason', models.CharField(blank=True, max_length=100, null=True)),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='diagnosis.diagnosis')),
            ],
        ),
    ]
